/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 egyptian_temple_v010.glb -I 
Files: egyptian_temple_v010.glb [152.45MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/egyptian_temple_v010-transformed.glb [4.74MB] (97%)
*/

import React, { useContext, useEffect, useRef } from 'react';
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei';

const context = React.createContext();

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/glbs/egyptian_temple_v010_transformed.glb');
  const instances = React.useMemo(
    () => ({
      Mesh: nodes.Mesh,
      Mesh1: nodes.Mesh_1,
      Mesh2: nodes.Mesh025,
      Mesh3: nodes.Mesh025_1,
      OuterFloor: nodes.OuterFloor,
      Bush: nodes.Bush_01001,
      Mesh4: nodes.Mesh026,
      Mesh5: nodes.Mesh026_1,
      Torus: nodes.Torus015,
      Water: nodes.Water,
      Plane: nodes.Plane001,
      FrontOutside: nodes.FrontOutside001,
      Fence: nodes.Fence001,
      Fence1: nodes.Fence004,
      BackBorder: nodes.BackBorder,
      BackBorder1: nodes.BackBorder001,
      BackDoors: nodes.BackDoors,
      DoorA: nodes.DoorA,
      DoorA1: nodes.DoorA001,
      DoorB: nodes.DoorB,
      DoorB1: nodes.DoorB002,
      Floor: nodes.Floor,
      FrontBorder: nodes.FrontBorder,
      Mesh6: nodes.Mesh004,
      Mesh7: nodes.Mesh004_1,
      FrontWalls: nodes.FrontWalls,
      Pillars: nodes.Pillars,
      Roof: nodes.Roof,
      Roof1: nodes.Roof001,
      Roof2: nodes.Roof002,
      Roof3: nodes.Roof003,
      BackInner: nodes.BackInner,
      BackInner1: nodes.BackInner001,
    }),
    [nodes]
  );
  return (
    <Merged
      meshes={instances}
      {...props}>
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}

export function Model({ children, gltfLoaded, ...props }) {
  const instances = useContext(context);
  const group = useRef();
  const { nodes, animations } = useGLTF('/glbs/egyptian_temple_v010_transformed.glb');
  const { mixer, actions } = useAnimations(animations, group);

  useEffect(() => {
    gltfLoaded(nodes, animations, mixer, actions);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <group name="Scene">
        {children}
        {/* <group
          name="CameraTarget"
          position={[7.864, 2.193, -3.38]}
        />
        <group
          name="Empty"
          position={[0, 2.358, 30]}
        /> */}
        <PerspectiveCamera
          name="WebCamera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={41.112}
          position={[-30.065, 12.551, 42.995]}
          rotation={[-0.22, -0.674, -0.138]}
        />
        <group
          name="MiddleLeft"
          position={[-5.727, 3.92, 0.19]}
          scale={0.01}>
          <instances.Mesh name="Mesh" />
          <instances.Mesh1 name="Mesh_1" />
        </group>
        <group
          name="MiddleRight001"
          position={[8.523, -0.049, -7.014]}
          rotation={[Math.PI, 0, 0]}
          scale={-1}>
          <instances.Mesh2 name="Mesh025" />
          <instances.Mesh3 name="Mesh025_1" />
        </group>
        <instances.OuterFloor name="OuterFloor" />
        <instances.Bush
          name="Bush_01001"
          position={[-13.208, 0.293, -15.518]}
          rotation={[0, 0.076, 0]}
          scale={[1.201, 1.416, 1.538]}
        />
        <group
          name="Tree004"
          position={[-28.06, 0.4, -17.441]}
          rotation={[Math.PI, -1.547, Math.PI]}
          scale={3.083}>
          <instances.Mesh4 name="Mesh026" />
          <instances.Mesh5 name="Mesh026_1" />
        </group>
        <instances.Torus
          name="Torus015"
          position={[-0.594, 0.913, 0.839]}
        />
        <instances.Water
          name="Water"
          position={[2.161, 0, -2.574]}
        />
        <instances.Plane
          name="Plane001"
          position={[2.161, 0, -2.574]}
        />
        <instances.FrontOutside
          name="FrontOutside001"
          position={[2.161, 0, -2.574]}
        />
        <instances.Fence
          name="Fence001"
          position={[-13.411, 1.297, 0.935]}
          rotation={[0, 0.442, 0]}
        />
        <instances.Fence1
          name="Fence004"
          position={[-13.411, 1.297, 0.935]}
          rotation={[0, 0.442, 0]}
        />
        <instances.BackBorder
          name="BackBorder"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.BackBorder1
          name="BackBorder001"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.BackDoors
          name="BackDoors"
          position={[4.571, 4.546, -19.839]}
          rotation={[0, -1.098, 0]}
        />
        <instances.DoorA
          name="DoorA"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.DoorA1
          name="DoorA001"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.DoorB
          name="DoorB"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.DoorB1
          name="DoorB002"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.Floor
          name="Floor"
          position={[0.233, 0.116, -0.227]}
          scale={0.01}
        />
        <instances.FrontBorder
          name="FrontBorder"
          position={[-1.563, 0.006, -0.01]}
        />
        <group
          name="FrontDoor"
          position={[-5.008, 0.006, -0.01]}>
          <instances.Mesh6 name="Mesh004" />
          <instances.Mesh7 name="Mesh004_1" />
        </group>
        <instances.FrontWalls
          name="FrontWalls"
          position={[-1.563, 0.006, -0.01]}
        />
        <instances.Pillars
          name="Pillars"
          position={[-1.574, 0.006, -0.067]}
        />
        <instances.Roof
          name="Roof"
          position={[0.281, 8.751, 0.319]}
          scale={0.01}
        />
        <instances.Roof1
          name="Roof001"
          position={[0.184, 8.751, 0.319]}
          scale={0.01}
        />
        <instances.Roof2
          name="Roof002"
          position={[0.184, 8.751, 0.319]}
          scale={0.01}
        />
        <instances.Roof3
          name="Roof003"
          position={[0.184, 8.751, 0.319]}
          scale={0.01}
        />
        <instances.BackInner
          name="BackInner"
          position={[-4.388, 0.611, -17.069]}
          scale={0.01}
        />
        <instances.BackInner1
          name="BackInner001"
          position={[-4.388, 0.611, -17.069]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glbs/egyptian_temple_v010_transformed.glb');
