/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 aquarium_01.glb -I 
Files: aquarium_01.glb [157.24MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/aquarium_01-transformed.glb [10.94MB] (93%)
*/

import React from 'react'
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei'

const context = React.createContext()

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/aquarium_01-transformed.glb')
  const instances = React.useMemo(
    () => ({
      Sphere: nodes.Sphere009,
      Cube: nodes.Cube002,
      Wall: nodes.Wall_1020,
      Plane: nodes.Plane013,
      Plane1: nodes.Plane013_1,
      TopBuilding: nodes.Top_Building_1,
      Plane2: nodes.Plane003,
      Cube1: nodes.Cube020,
      Cube2: nodes.Cube020_1,
      Wall1: nodes.Wall_1016,
      EntranceTunnelWall: nodes.EntranceTunnelWall001,
      BigAquarium: nodes.BigAquarium,
      Aquarium: nodes.Aquarium_1,
      Aquarium1: nodes.Aquarium_2,
      Bench: nodes.Bench,
      Plane3: nodes.Plane008,
      Plane4: nodes.Plane008_1,
      Plane5: nodes.Plane008_2,
      CalatheaLeaves: nodes.calathea_Leaves,
      Plant: nodes.plant001,
      BushMediteranean: nodes.Bush_Mediteranean002,
      EntranceTunnelWall1: nodes.EntranceTunnelWall,
      BackWall: nodes.BackWall,
      Entrance: nodes.Entrance,
      Circle: nodes.Circle,
      Circle1: nodes.Circle_1,
      SideWall: nodes.SideWall,
      BackRocks: nodes.BackRocks,
      EntranceBackGlass: nodes.entranceBackGlass,
      FloorWalls: nodes.Floor_Walls001,
      Roof: nodes.Roof,
      FloorWalls1: nodes.Floor_Walls003,
      BzierCurve: nodes.BézierCurve,
      Cube3: nodes.Cube008,
      OutsideFloor: nodes.OutsideFloor,
      OutsideFloor1: nodes.OutsideFloor001,
      OutsideFloor2: nodes.OutsideFloor002,
      RockWall: nodes.RockWall_2,
      RockWall1: nodes.RockWall,
      RockyWall: nodes.RockyWall,
      Wood: nodes.Wood,
      Aquabuitenregisteredresmmptmmst: nodes['aqua_00-00-01_buiten-registered_res_15mm_pt_5mm_18_st_9001'],
      Aquabuitenregisteredresmmptmmst1: nodes['aqua_00-00-01_buiten-registered_res_15mm_pt_5mm_18_st_9001_1'],
      Plane6: nodes.Plane004,
      Plane7: nodes.Plane006,
      Plane8: nodes.Plane021,
      Plane9: nodes.Plane051,
      Plane10: nodes.Plane032,
      Plane11: nodes.Plane032_1,
      MobileTreeTreeLeaf: nodes.Mobile_Tree_2_Tree_Leaf_0004_1,
      MobileTreeTreeLeaf1: nodes.Mobile_Tree_2_Tree_Leaf_0004_2,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = React.useContext(context)
  const group = React.useRef()
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MovieTarget" position={[-7.073, 6.091, -8.813]} />
        <PerspectiveCamera name="WebCamera" makeDefault={false} far={1000} near={0.1} fov={44.096} position={[11.42, 15.108, -29.026]} rotation={[-2.722, 0.696, 2.863]} />
        <instances.Sphere name="Sphere009" position={[7.403, 4.444, -0.503]} rotation={[Math.PI, 0, Math.PI]} scale={0.121} />
        <instances.Cube name="Cube002" position={[-80.154, -5.164, 53.262]} />
        <instances.Wall name="Wall_1020" position={[-3.215, 1.509, 3.841]} />
        <group name="LeftTemple" position={[2.216, 8.853, 6.794]} rotation={[-Math.PI / 2, 0, 0]}>
          <instances.Plane name="Plane013" />
          <instances.Plane1 name="Plane013_1" />
        </group>
        <instances.TopBuilding name="Top_Building_1" position={[-24.676, 9.206, -0.066]} rotation={[-Math.PI / 2, 0, 0]} />
        <instances.Plane2 name="Plane003" position={[-24.676, 9.206, -0.066]} rotation={[-Math.PI / 2, 0, 0]} />
        <group name="BigWall_1" position={[-11.115, 1.701, 4.087]}>
          <instances.Cube1 name="Cube020" />
          <instances.Cube2 name="Cube020_1" />
        </group>
        <instances.Wall1 name="Wall_1016" position={[-23.691, 1.701, 4.089]} />
        <instances.EntranceTunnelWall name="EntranceTunnelWall001" position={[-44.421, 1.993, 7.522]} rotation={[-Math.PI, 0, -Math.PI]} />
        <instances.BigAquarium name="BigAquarium" position={[-49.167, -2.137, 8.012]} />
        <instances.Aquarium name="Aquarium_1" position={[-17.422, 1.514, 4.26]} />
        <instances.Aquarium1 name="Aquarium_2" position={[-23.736, -0.646, 12.227]} rotation={[-Math.PI, 0, -Math.PI]} />
        <instances.Bench name="Bench" position={[-38.448, -1.498, 8.009]} scale={0.179} />
        <group name="Floor_Walls002" position={[-24.249, 5.072, 7.891]}>
          <instances.Plane3 name="Plane008" />
          <instances.Plane4 name="Plane008_1" />
          <instances.Plane5 name="Plane008_2" />
        </group>
        <instances.CalatheaLeaves name="calathea_Leaves" position={[6.539, -0.151, 14.734]} rotation={[-Math.PI, 0.396, -Math.PI]} scale={3.642} />
        <instances.Plant name="plant001" position={[4.499, 0.834, 14.942]} rotation={[Math.PI, 0, Math.PI]} scale={2.991} />
        <instances.BushMediteranean name="Bush_Mediteranean002" position={[0.726, -0.654, 15.099]} rotation={[Math.PI, -0.989, Math.PI]} scale={0.35} />
        <instances.EntranceTunnelWall1 name="EntranceTunnelWall" position={[-2.787, 1.993, 8.441]} />
        <instances.BackWall name="BackWall" position={[2.416, 5.479, 16.14]} />
        <instances.Entrance name="Entrance" position={[2.416, 1.985, -0.012]} />
        <group name="Pond_1" position={[-2.769, -1.642, 8.07]}>
          <instances.Circle name="Circle" />
          <instances.Circle1 name="Circle_1" />
        </group>
        <instances.SideWall name="SideWall" position={[7.812, 5.479, 8.14]} rotation={[0, 1.571, 0]} />
        <instances.BackRocks name="BackRocks" position={[2.478, -0.757, 14.697]} />
        <instances.EntranceBackGlass name="entranceBackGlass" position={[2.06, 0.18, 16.087]} rotation={[-Math.PI / 2, 0, 0]} />
        <instances.FloorWalls name="Floor_Walls001" position={[-24.249, 5.072, 7.891]} />
        <instances.Roof name="Roof" position={[7.656, 4.998, 1.871]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <instances.FloorWalls1 name="Floor_Walls003" position={[-26.17, -2.106, 8.033]} />
        <instances.BzierCurve name="BézierCurve" position={[-49.161, -1.825, 8.076]} rotation={[-Math.PI, 1.484, -Math.PI]} />
        <instances.Cube3 name="Cube008" position={[-48.76, -2.124, 11.27]} />
        <instances.OutsideFloor name="OutsideFloor" position={[2.796, -2.09, -1.993]} />
        <instances.OutsideFloor1 name="OutsideFloor001" position={[2.796, -2.09, -1.993]} />
        <instances.OutsideFloor2 name="OutsideFloor002" position={[2.796, -2.09, -1.993]} />
        <instances.RockWall name="RockWall_2" position={[8.982, 3.153, 4.275]} rotation={[-0.415, -0.465, 0.544]} scale={[2.458, 3.619, 2.357]} />
        <instances.RockWall1 name="RockWall" position={[-5.576, 5.003, -1.025]} scale={[1.666, 2.453, 1.597]} />
        <instances.RockyWall name="RockyWall" position={[-8.743, 0.894, -24.412]} scale={0.585} />
        <instances.Wood name="Wood" position={[-3.707, -0.275, -5.227]} rotation={[0, -0.175, 0]} />
        <group name="Rocks_2_HighPoly" rotation={[0, -1.571, 0]}>
          <instances.Aquabuitenregisteredresmmptmmst name="aqua_00-00-01_buiten-registered_res_15mm_pt_5mm_18_st_9001" />
          <instances.Aquabuitenregisteredresmmptmmst1 name="aqua_00-00-01_buiten-registered_res_15mm_pt_5mm_18_st_9001_1" />
        </group>
        <instances.Plane6 name="Plane004" position={[-48.088, 7.167, -13.831]} rotation={[Math.PI / 2, 0, -1.309]} scale={1.121} />
        <instances.Plane7 name="Plane006" position={[1.497, 5.033, -3.923]} rotation={[1.735, 0.014, -3.137]} scale={1.573} />
        <instances.Plane8 name="Plane021" position={[-2.967, 6.716, -2.41]} rotation={[1.658, 0, 0]} scale={0.508} />
        <instances.Plane9 name="Plane051" position={[-48.607, 6.532, -9.395]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Tree_Leafs005" position={[-4.672, 5.695, -16.782]} rotation={[-0.241, -0.596, -0.145]} scale={0.598}>
          <instances.Plane10 name="Plane032" />
          <instances.Plane11 name="Plane032_1" />
        </group>
        <group name="Mobile_Tree_2_Tree_Leaf_0004" position={[-5.311, -0.754, -6.36]} rotation={[-Math.PI, 1.41, -Math.PI]} scale={0.009}>
          <instances.MobileTreeTreeLeaf name="Mobile_Tree_2_Tree_Leaf_0004_1" />
          <instances.MobileTreeTreeLeaf1 name="Mobile_Tree_2_Tree_Leaf_0004_2" />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/aquarium_01-transformed.glb')
