/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 wintertuin_v03.glb -I 
Files: wintertuin_v03.glb [65.46MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/wintertuin_v03-transformed.glb [2.59MB] (96%)
*/

import React, { useRef, useContext, useEffect } from 'react';
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei';

const context = React.createContext();

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/glbs/wintertuin_v03-transformed.glb');
  const instances = React.useMemo(
    () => ({
      Cube: nodes.Cube010,
      Plane: nodes.Plane,
      Plane1: nodes.Plane_1,
      Ground: nodes.Ground,
      Spiegel: nodes.Spiegel,
      Vloer: nodes.Vloer,
      WintertuinStandbeeldLP: nodes.Wintertuin_Standbeeld_LP,
      Rotsen: nodes.Rotsen01,
      Rotsen1: nodes.Rotsen02,
      Smallrocksmallrocks: nodes.smallrock1_smallrocks_0,
      Plant: nodes.Plant,
    }),
    [nodes]
  );
  return (
    <Merged
      meshes={instances}
      {...props}>
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}

export function Model({ children, gltfLoaded, ...props }) {
  const instances = useContext(context);
  const group = useRef();
  const { nodes, animations } = useGLTF('/glbs/wintertuin_v03-transformed.glb');
  const { mixer, actions } = useAnimations(animations, group);

  useEffect(() => {
    gltfLoaded(nodes, animations, mixer, actions);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <group name="Scene">
        {children}
        <PerspectiveCamera
          name="Camera001"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={80.312}
          position={[-16.253, 2, -8.66]}
          rotation={[1.806, 1.519, -1.806]}
        />
        <PerspectiveCamera
          name="Camera002"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={96.733}
          position={[-12.742, 2.897, -13.267]}
          rotation={[0.337, 0, 0]}
        />
        <PerspectiveCamera
          name="Camera003"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={53.702}
          position={[-7.153, 0.653, -7.625]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <PerspectiveCamera
          name="Camera004"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={61.555}
          position={[-12.881, 2, -5.277]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <PerspectiveCamera
          name="WebCamera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={49.426}
          position={[-12.876, 1.178, 1.755]}
        />
        <instances.Cube
          name="Cube010"
          position={[-3.784, 0.235, -7.313]}
        />
        <group
          name="Gebouw"
          rotation={[0, 0, -Math.PI / 2]}>
          <instances.Plane name="Plane" />
          <instances.Plane1 name="Plane_1" />
        </group>
        <instances.Ground
          name="Ground"
          position={[-22.392, -0.828, -7.345]}
        />
        <instances.Spiegel
          name="Spiegel"
          position={[-30.166, 0.497, -4.844]}
        />
        <instances.Vloer
          name="Vloer"
          position={[-1.475, -1, -10.371]}
        />
        <instances.WintertuinStandbeeldLP
          name="Wintertuin_Standbeeld_LP"
          position={[-24.107, -0.187, -8.914]}
        />
        <instances.Rotsen
          name="Rotsen01"
          position={[-22.936, 1.368, -2.84]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <instances.Rotsen1
          name="Rotsen02"
          position={[-30.945, 0.348, -2.919]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <instances.Smallrocksmallrocks
          name="smallrock1_smallrocks_0"
          position={[-19.819, -1.027, -5.84]}
          rotation={[0, -0.698, 0]}
        />
        <instances.Plant
          name="Plant"
          position={[-8.32, -0.996, -7.341]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glbs/wintertuin_v03-transformed.glb');
