/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 grand_cafe_flamingo_v07.glb -I 
Files: grand_cafe_flamingo_v07.glb [282.07MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/grand_cafe_flamingo_v07-transformed.glb [9.31MB] (97%)
*/

import React, { useContext, useEffect, useRef } from 'react';
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei';
import * as THREE from 'three';

const context = React.createContext();

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/glbs/grand_cafe_flamingo_v10_transformed.glb');
  const instances = React.useMemo(
    () => ({
      MobileTreeTreeLeaf: nodes.Mobile_Tree_2_Tree_Leaf_0001_1,
      MobileTreeTreeLeaf1: nodes.Mobile_Tree_2_Tree_Leaf_0001_2,
      Seats: nodes.Seats_1,
      Bar: nodes.Bar,
      CubeSeats: nodes.CubeSeats,
      Closet: nodes.Closet001,
      CornerSeat: nodes.CornerSeat,
      Pictuters: nodes.Pictuters,
      BigSeat: nodes.BigSeat002,
      Cube: nodes.Cube005,
      Cube1: nodes.Cube005_1,
      CornerProps: nodes.CornerProps,
      Cube2: nodes.Cube018,
      Cube3: nodes.Cube018_1,
      Cube4: nodes.Cube028,
      Cube5: nodes.Cube028_1,
      Cylinder: nodes.Cylinder,
      Cylinder1: nodes.Cylinder_1,
      WindowsSecondePart: nodes.Windows_SecondePart,
      Mesh: nodes.Mesh022,
      Mesh1: nodes.Mesh022_1,
      RoofSecondPart: nodes.Roof_Second_Part,
      Terras: nodes.Terras,
      Wall: nodes.Wall_1001,
      RoofBalistrate: nodes.RoofBalistrate,
      TopCeiling: nodes.topCeiling,
      RoofBackSide: nodes.RoofBackSide,
      GlassWall: nodes.GlassWall,
      RoofPillars: nodes.RoofPillars,
      Glass: nodes.Glass,
      BackgroundWall: nodes.BackgroundWall,
      BackgroundTrees: nodes.Background_Trees,
      Bushes: nodes.bushes,
      BackGroundForrest: nodes.BackGroundForrest,
      TreeCutTreeCut: nodes.TreeCut_TreeCut_0001,
      WallSmallIce: nodes.Wall_1_Small_Ice,
      WallSmallBlack: nodes.Wall_1_SmallBlack,
      WallTransParent: nodes.Wall_1_TransParent,
      Closet1: nodes.Closet,
      Poster: nodes.Poster,
      Skulls: nodes.Skulls,
      Statue: nodes.Statue,
      Cylinder2: nodes.Cylinder020,
      BushMediteranean: nodes.Bush_Mediteranean001,
      TreeLeafs: nodes.Tree_Leafs001,
      Mesh2: nodes.Mesh045,
      Mesh3: nodes.Mesh045_1,
      Mesh4: nodes.Mesh050,
      Mesh5: nodes.Mesh050_1,
      BigRoof: nodes.BigRoof,
      InsideWalls: nodes.InsideWalls_2,
      InsideFloor: nodes.insideFloor,
      Cylinder3: nodes.Cylinder018,
      Sphere: nodes.Sphere,
      Sphere1: nodes.Sphere_1,
      TreePot: nodes.TreePot,
      PantherStatueStandPiece: nodes.PantherStatue_StandPiece,
      PanterStandbeeld: nodes.PanterStandbeeld,
      Outsideseats: nodes.Outside_seats026,
      Grass: nodes.Grass,
      GrassHovel: nodes.GrassHovel,
      CToren: nodes['C-Toren'],
      Cube6: nodes.Cube001,
      Plane: nodes.Plane,
      Station: nodes.Station,
      FourthBuilding: nodes.FourthBuilding,
      Towers: nodes.Towers,
      ZooAntwerpenKameelLP: nodes.Zoo_Antwerpen_KameelLP,
      SeatsSecondPart: nodes.Seats_Second_Part,
      LongTable: nodes.LongTable001,
    }),
    [nodes]
  );
  return (
    <Merged
      meshes={instances}
      {...props}>
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}
export function Model({ children, gltfLoaded, ...props }) {
  const instances = useContext(context);
  const group = useRef();
  const { nodes, animations } = useGLTF('/glbs/grand_cafe_flamingo_v10_transformed.glb');
  const { mixer, actions } = useAnimations(animations, group);

  useEffect(() => {
    const loader = new THREE.TextureLoader();
    loader.load('/img/grandcafeflamingo_alphamap.png', function (textureCubeAlpha) {
      nodes.Glass.material.alphaMap = textureCubeAlpha;
      nodes.Glass.material.alphaMap.opacity = 1;
      nodes.GlassWall.material.alphaMap = textureCubeAlpha;
      nodes.GlassWall.material.alphaMap.opacity = 1;
      nodes.Windows_SecondePart.material.alphaMap = textureCubeAlpha;
      nodes.Windows_SecondePart.material.opacity = 1;
      nodes.GlasDoor.children[1].material.alphaMap = textureCubeAlpha;
      nodes.GlasDoor.children[1].material.opacity = 0.5;
      nodes.Closet.material.alphaMap = textureCubeAlpha;
      nodes.Closet.material.opacity = 1;
      // nodes.SecondePart_Transparent.material.alphaMap = textureCubeAlpha;
      // nodes.SecondePart_Transparent.material.opacity = 1;
      nodes.Wall_1_TransParent.material.alphaMap = textureCubeAlpha;
      nodes.Wall_1_TransParent.material.opacity = 0.4;

      // nodes.Outside_seats026.material.transparent = false;
      // nodes.Outside_seats026.material.opacity = 1.0;

      console.log(nodes);
    });

    gltfLoaded(nodes, animations, mixer, actions);

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <group name="Scene">
        {children}
        <group
          name="MovieLookAtPoint_2"
          position={[2.039, 3.356, 2.928]}
        />
        <PerspectiveCamera
          name="WebCamera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={44.096}
          position={[10.286, 7.382, 41.961]}
          rotation={[-0.103, 0.207, 0.021]}
        />
        <group
          name="Mobile_Tree_2_Tree_Leaf_0001"
          position={[-44.256, -0.711, 8.926]}
          rotation={[0, 0.436, 0]}
          scale={0.007}>
          <instances.MobileTreeTreeLeaf name="Mobile_Tree_2_Tree_Leaf_0001_1" />
          <instances.MobileTreeTreeLeaf1 name="Mobile_Tree_2_Tree_Leaf_0001_2" />
        </group>
        <instances.Seats
          name="Seats_1"
          position={[4.05, 1.882, -6.125]}
        />
        <instances.Bar
          name="Bar"
          position={[-3.038, 0.128, -15.415]}
        />
        <instances.CubeSeats
          name="CubeSeats"
          position={[4.678, 0.606, -2.489]}
        />
        <instances.Closet
          name="Closet001"
          position={[10.119, 0.59, -0.5]}
        />
        <instances.CornerSeat
          name="CornerSeat"
          position={[-7.046, 0.5, -12.773]}
        />
        <instances.Pictuters
          name="Pictuters"
          position={[-7.792, 1.914, -12.575]}
        />
        <instances.BigSeat
          name="BigSeat002"
          position={[5.703, 0.324, -0.24]}
        />
        <group
          name="BigTable_SideRoom"
          position={[-15.44, 0.502, -4.48]}
          rotation={[0, 1.571, 0]}>
          <instances.Cube name="Cube005" />
          <instances.Cube1 name="Cube005_1" />
        </group>
        <instances.CornerProps
          name="CornerProps"
          position={[-7.2, 1.021, -14.237]}
        />
        <group
          name="WoodenCloset"
          position={[14.705, 1.631, -8.418]}
          rotation={[0, -1.571, 0]}>
          <instances.Cube2 name="Cube018" />
          <instances.Cube3 name="Cube018_1" />
        </group>
        <group
          name="GlasDoor"
          position={[-12.432, 2.184, -8.805]}>
          <instances.Cube4 name="Cube028" />
          <instances.Cube5 name="Cube028_1" />
        </group>
        <group
          name="Cylinder013"
          position={[-15.062, 4.287, -8.823]}>
          <instances.Cylinder name="Cylinder" />
          <instances.Cylinder1 name="Cylinder_1" />
        </group>
        <instances.WindowsSecondePart
          name="Windows_SecondePart"
          position={[11.976, 3.57, 1.586]}
        />
        <group
          name="Pillars_First_Part"
          position={[-12.786, -0.435, 1.272]}>
          <instances.Mesh name="Mesh022" />
          <instances.Mesh1 name="Mesh022_1" />
        </group>
        <instances.RoofSecondPart
          name="Roof_Second_Part"
          position={[15.904, 8.453, -4.71]}
        />
        <instances.Terras
          name="Terras"
          position={[-0.902, -0.247, -4.176]}
        />
        <instances.Wall
          name="Wall_1001"
          position={[-13.775, -0.435, 1.441]}
        />
        <instances.RoofBalistrate
          name="RoofBalistrate"
          position={[9.962, 9.466, -10.937]}
        />
        <instances.TopCeiling
          name="topCeiling"
          position={[-5.621, 7.173, -3.169]}
        />
        <instances.RoofBackSide
          name="RoofBackSide"
          position={[-15.246, 0.054, -10.309]}
          rotation={[0, -1.571, 0]}
        />
        <instances.GlassWall
          name="GlassWall"
          position={[-17.327, 0.054, -9.062]}
        />
        <instances.RoofPillars
          name="RoofPillars"
          position={[11.001, 9.069, 1.589]}
        />
        <instances.Glass
          name="Glass"
          position={[-13.775, -0.435, 1.432]}
        />
        <instances.BackgroundWall
          name="BackgroundWall"
          position={[100.742, 0.934, -62.284]}
          rotation={[0, -1.484, 0]}
        />
        <instances.BackgroundTrees
          name="Background_Trees"
          position={[-255.203, 21.557, -65.769]}
          rotation={[0, 0.12, -Math.PI / 2]}
          scale={22.429}
        />
        <instances.Bushes
          name="bushes"
          position={[-14.772, -2.147, -47.804]}
          rotation={[Math.PI / 2, 1.571, 0]}
          scale={[8.71, 4.584, 4.584]}
        />
        <instances.BackGroundForrest
          name="BackGroundForrest"
          position={[-6.232, 9.11, 49.993]}
          rotation={[0, -1.509, 0]}
          scale={54.902}
        />
        <instances.TreeCutTreeCut
          name="TreeCut_TreeCut_0001"
          position={[92.529, 0.069, -26.809]}
          rotation={[0, -1.403, 0]}
          scale={1.656}
        />
        <instances.WallSmallIce
          name="Wall_1_Small_Ice"
          position={[-18.877, 3.663, -0.937]}
        />
        <instances.WallSmallBlack
          name="Wall_1_SmallBlack"
          position={[-13.775, -0.435, 1.441]}
        />
        <instances.WallTransParent
          name="Wall_1_TransParent"
          position={[-13.775, -0.435, 1.441]}
        />
        <instances.Closet1
          name="Closet"
          position={[-11.749, 1.605, -1.003]}
        />
        <instances.Poster
          name="Poster"
          position={[-11.877, 2.739, -0.685]}
        />
        <instances.Skulls
          name="Skulls"
          position={[-11.767, 1.418, -2.419]}
        />
        <instances.Statue
          name="Statue"
          position={[-11.832, 1.297, 0.408]}
        />
        <instances.Cylinder2
          name="Cylinder020"
          position={[-23.219, 5.344, 4.836]}
          scale={6.732}
        />
        <instances.BushMediteranean
          name="Bush_Mediteranean001"
          position={[-19.532, -0.3, 10.945]}
          rotation={[0, -1.396, 0]}
          scale={0.479}
        />
        <instances.TreeLeafs
          name="Tree_Leafs001"
          position={[-22.886, 11.381, 4.553]}
          rotation={[-0.241, -0.596, -0.145]}
        />
        <group
          name="Walls_2"
          position={[1.199, 3.608, -8.18]}>
          <instances.Mesh2 name="Mesh045" />
          <instances.Mesh3 name="Mesh045_1" />
        </group>
        <group
          name="TussenWall"
          position={[10.267, 3.45, -4.564]}>
          <instances.Mesh4 name="Mesh050" />
          <instances.Mesh5 name="Mesh050_1" />
        </group>
        <instances.BigRoof
          name="BigRoof"
          position={[-5.116, 5.865, -3.223]}
        />
        <instances.InsideWalls
          name="InsideWalls_2"
          position={[-14.875, 2.165, -7.279]}
        />
        <instances.InsideFloor
          name="insideFloor"
          position={[-0.902, -0.247, -4.176]}
        />
        <instances.Cylinder3
          name="Cylinder018"
          position={[1.404, 0.691, -4.65]}
        />
        <group
          name="Fence_Part_1003"
          position={[-19.065, 1.007, 1.879]}>
          <instances.Sphere name="Sphere" />
          <instances.Sphere1 name="Sphere_1" />
        </group>
        <instances.TreePot
          name="TreePot"
          position={[-23.288, 0.078, 4.636]}
        />
        <instances.PantherStatueStandPiece
          name="PantherStatue_StandPiece"
          position={[-18.816, 0.266, 11.091]}
        />
        <instances.PanterStandbeeld
          name="PanterStandbeeld"
          position={[-18.874, 1.303, 11.257]}
        />
        <instances.Outsideseats
          name="Outside_seats026"
          position={[19.966, 0.57, 8.21]}
          rotation={[0, 1.426, 0]}
        />
        <instances.Grass
          name="Grass"
          position={[4.122, 0.425, -5.942]}
        />
        <instances.GrassHovel
          name="GrassHovel"
          position={[-11.77, -0.117, 10.863]}
        />
        <instances.CToren
          name="C-Toren"
          position={[66.242, 26.22, -113.954]}
          rotation={[Math.PI, -1.501, Math.PI]}
        />
        <instances.Cube6
          name="Cube001"
          position={[35.643, 2.627, -37.844]}
        />
        <instances.Plane
          name="Plane"
          position={[-9.109, -0.055, 13.57]}
        />
        <instances.Station
          name="Station"
          position={[-63.514, 0.413, -140.092]}
        />
        <instances.FourthBuilding
          name="FourthBuilding"
          position={[111.397, 2.804, -81.601]}
          rotation={[-Math.PI, -1.309, -1.571]}
        />
        <instances.Towers
          name="Towers"
          position={[92.739, 0, -81.177]}
          rotation={[Math.PI, -1.494, Math.PI]}
        />
        <instances.ZooAntwerpenKameelLP
          name="Zoo_Antwerpen_KameelLP"
          position={[101.652, 21.284, -81.225]}
          rotation={[Math.PI / 2, 0, 1.833]}
        />
        <instances.SeatsSecondPart
          name="Seats_Second_Part"
          position={[12.327, 0.641, 0.102]}
        />
        <instances.LongTable
          name="LongTable001"
          position={[4.31, 0.987, -10.744]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glbs/grand_cafe_flamingo_v10_transformed.glb');
