/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 inkom.glb -I 
Files: inkom.glb [146.95MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/inkom-transformed.glb [4.8MB] (97%)
*/

import React, { useContext, useEffect, useRef } from 'react';
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei';

const context = React.createContext();

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/glbs/entrance_pavilion_v27_transformed.glb');
  const instances = React.useMemo(
    () => ({
      Cylinder: nodes.Cylinder,
      AstridpleinPlattegrond: nodes.AstridpleinPlattegrond_1,
      AstridpleinPlattegrond1: nodes.AstridpleinPlattegrond_2,
      Cube: nodes.Cube001,
      TorenLP: nodes.Toren1LP,
      TorenLP1: nodes.Toren2LP,
      ZooAntwerpenKameelLP: nodes.Zoo_Antwerpen_KameelLP,
      Object: nodes.Object_1,
      Object1: nodes.Object_1_1,
      MobileTreeTreeLeaf: nodes.Mobile_Tree_2_Tree_Leaf_0002_1,
      MobileTreeTreeLeaf1: nodes.Mobile_Tree_2_Tree_Leaf_0002_2,
      TreeCutTreeCut: nodes.TreeCut_TreeCut_0,
      Sphere: nodes.Sphere,
      Plane: nodes.Plane006,
      Plane1: nodes.Plane006_1,
      Ground: nodes.Ground,
      GrassgreenGrassgreen: nodes.Grass_green013_Grass_green001_0,
      ThirdBuilding: nodes.ThirdBuilding,
      FirstBuildings: nodes.FirstBuildings,
      SecondBuilding: nodes.SecondBuilding,
      FourthBuilding: nodes.FourthBuilding,
      Building: nodes['153_211_Building_0001'],
      ID: nodes.ID1223001,
      ID1: nodes.ID1223001_1,
      ID2: nodes.ID1223001_2,
      Towers: nodes.Towers,
    }),
    [nodes]
  );
  return (
    <Merged
      meshes={instances}
      {...props}>
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}

export function Model({ children, gltfLoaded, ...props }) {
  const instances = useContext(context);
  const group = useRef();
  const { nodes, animations } = useGLTF('/glbs/entrance_pavilion_v27_transformed.glb');
  const { mixer, actions } = useAnimations(animations, group);

  useEffect(() => {
    gltfLoaded(nodes, animations, mixer, actions);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <group name="Scene">
        {children}
        <PerspectiveCamera
          name="WebCamera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={28.409}
          position={[-81.387, 27.687, -99.319]}
          rotation={[-2.805, -1.214, -2.824]}
        />
        <instances.Cylinder
          name="Cylinder"
          position={[17.751, 0.089, -60.214]}
          rotation={[0, -0.228, 0]}
          scale={2.351}
        />
        <group
          name="AstridpleinPlattegrond"
          position={[-13.168, 0, -123.055]}
          scale={105.304}>
          <instances.AstridpleinPlattegrond name="AstridpleinPlattegrond_1" />
          <instances.AstridpleinPlattegrond1 name="AstridpleinPlattegrond_2" />
        </group>
        <instances.Cube
          name="Cube001"
          position={[19.476, 0, -36.397]}
        />
        <instances.TorenLP
          name="Toren1LP"
          position={[29.505, 9.63, -24.139]}
        />
        <instances.TorenLP1
          name="Toren2LP"
          position={[30.119, 10.275, -13.456]}
        />
        <instances.ZooAntwerpenKameelLP
          name="Zoo_Antwerpen_KameelLP"
          position={[26.513, 21.284, -31.655]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group
          name="Object_5"
          position={[19.072, 0, -80.707]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.546}>
          <instances.Object name="Object_1" />
          <instances.Object1 name="Object_1_1" />
        </group>
        <group
          name="Mobile_Tree_2_Tree_Leaf_0002"
          position={[86.575, 0, -33.124]}
          scale={0.009}>
          <instances.MobileTreeTreeLeaf name="Mobile_Tree_2_Tree_Leaf_0002_1" />
          <instances.MobileTreeTreeLeaf1 name="Mobile_Tree_2_Tree_Leaf_0002_2" />
        </group>
        <instances.TreeCutTreeCut
          name="TreeCut_TreeCut_0"
          position={[83.765, 0, -48.752]}
          rotation={[0, -0.95, 0]}
          scale={2.612}
        />
        <instances.Sphere
          name="Sphere"
          position={[163.53, 1.209, 9.009]}
          rotation={[0, 1.021, 0]}
          scale={54.902}
        />
        <group
          name="Plane001"
          position={[23.828, -0.082, 0]}>
          <instances.Plane name="Plane006" />
          <instances.Plane1 name="Plane006_1" />
        </group>
        <instances.Ground
          name="Ground"
          position={[14.16, 0, -57.855]}
        />
        <instances.GrassgreenGrassgreen
          name="Grass_green013_Grass_green001_0"
          position={[95.443, -1.647, -42.274]}
          rotation={[-Math.PI, 1.267, -Math.PI]}
          scale={3.171}
        />
        <instances.ThirdBuilding
          name="ThirdBuilding"
          position={[40.94, 8.459, -63.778]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <instances.FirstBuildings
          name="FirstBuildings"
          position={[24.865, 11.689, -70.216]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <instances.SecondBuilding
          name="SecondBuilding"
          position={[24.865, 11.689, -70.216]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <instances.FourthBuilding
          name="FourthBuilding"
          position={[24.381, 2.804, -42.091]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <instances.Building
          name="153_211_Building_0001"
          position={[-22.097, 23.984, 35.035]}
          rotation={[0, 0.029, 0]}
        />
        <group
          name="Station"
          position={[12.351, 29.74, -11.973]}
          rotation={[0, -1.571, 0]}>
          <instances.ID name="ID1223001" />
          <instances.ID1 name="ID1223001_1" />
          <instances.ID2 name="ID1223001_2" />
        </group>
        <instances.Towers
          name="Towers"
          position={[29.62, 0, -24.179]}
          rotation={[0, 0.185, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glbs/entrance_pavilion_v27_transformed.glb');
