/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bird-building_v09.glb -I -T 
Files: bird-building_v09.glb [12.49MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/bird-building_v09-transformed.glb [7.75MB] (38%)
*/

import React, { useRef, useMemo, useContext, createContext, useEffect } from 'react';
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei';

const context = createContext();
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/glbs/bird-building_v09-transformed.glb');
  const instances = useMemo(
    () => ({
      MainBuilding: nodes.MainBuilding,
      SecondBuilding: nodes.SecondBuilding,
      ThirdBuilding: nodes.ThirdBuilding,
      Grass: nodes.Grass,
      TreeLeafs: nodes.Tree_Leafs,
      Trunks: nodes.Trunks,
      Branch: nodes.Branch,
      BushMediteranean: nodes.Bush_Mediteranean,
      Owl: nodes.Owl,
      OwlFoundation: nodes.Owl_Foundation,
      CharlesFoundation: nodes.Charles_Foundation,
      Charles: nodes.Charles,
      Plane: nodes.Plane001,
      Floor: nodes.Floor001,
      BushMediteranean1: nodes.Bush_Mediteranean001,
      SecondBuilding1: nodes.SecondBuilding001,
    }),
    [nodes]
  );
  return (
    <Merged
      meshes={instances}
      {...props}>
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}

export function Model({ children, gltfLoaded, ...props }) {
  const instances = useContext(context);
  const group = useRef();
  const { nodes, animations } = useGLTF('/glbs/bird-building_v09-transformed.glb');
  const { mixer, actions } = useAnimations(animations, group);

  useEffect(() => {
    gltfLoaded(nodes, animations, mixer, actions);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <group name="Scene">
        {children}
        <group
          name="LookAt"
          position={[5.982, 2.878, 12.624]}
        />
        <PerspectiveCamera
          name="WebCamera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.895}
          position={[28.555, 4.915, 40.681]}
          rotation={[-0.072, 0.676, 0.045]}
        />
        <instances.MainBuilding
          name="MainBuilding"
          position={[2.199, -0.531, 13.138]}
          rotation={[0, -1.571, 0]}
        />
        <instances.SecondBuilding
          name="SecondBuilding"
          position={[1.085, 2.342, 11.689]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <instances.ThirdBuilding
          name="ThirdBuilding"
          position={[-5.459, 0.23, -16.892]}
        />
        <instances.Grass
          name="Grass"
          position={[-8.854, -2.048, -12.549]}
          rotation={[-3.102, -0.312, -2.003]}
          scale={[0.142, 0.142, 0.097]}
        />
        <instances.TreeLeafs
          name="Tree_Leafs"
          position={[-8.496, 3.771, 21.634]}
          rotation={[-0.241, -0.596, -0.145]}
          scale={1.365}
        />
        <instances.Trunks
          name="Trunks"
          position={[-11.56, 0.857, 21.09]}
          scale={[0.409, 2.73, 0.409]}
        />
        <instances.Branch
          name="Branch"
          position={[-10.788, 4.573, 21.525]}
          rotation={[1.405, 0.99, -1.114]}
          scale={[0.136, 1.365, 0.136]}
        />
        <instances.BushMediteranean
          name="Bush_Mediteranean"
          position={[-13.704, -0.447, -16.476]}
          scale={0.03}
        />
        <instances.Owl
          name="Owl"
          position={[0.861, 1.129, 19.389]}
          rotation={[Math.PI / 2, 0, 0.175]}
          scale={2.323}
        />
        <instances.OwlFoundation
          name="Owl_Foundation"
          position={[1.257, 0.445, 16.629]}
          scale={2.323}
        />
        <instances.CharlesFoundation
          name="Charles_Foundation"
          position={[-12.329, 0.447, 23.14]}
          rotation={[0, -0.338, 0]}
          scale={2.226}
        />
        <instances.Charles
          name="Charles"
          position={[-13.856, 1.266, 27.434]}
          rotation={[Math.PI / 2, 0, 0.338]}
          scale={2.226}
        />
        <instances.Plane
          name="Plane001"
          position={[5.708, 5.541, 16.273]}
          rotation={[1.629, 0, 0]}
          scale={0.008}
        />
        <instances.Floor
          name="Floor001"
          position={[1.483, 0.795, -3.258]}
        />
        <instances.BushMediteranean1
          name="Bush_Mediteranean001"
          position={[-13.704, -0.447, -16.476]}
          scale={0.03}
        />
        <instances.SecondBuilding1
          name="SecondBuilding001"
          position={[1.085, 2.342, 11.689]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/glbs/bird-building_v09-transformed.glb');
