/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 cattlebuilding_v3.glb -I 
Files: cattlebuilding_v3.glb [196.4MB] > /Users/katiasmet/Projects/2023/yondr/zoo/static/glbs/cattlebuilding_v3-transformed.glb [7.15MB] (96%)
*/

import React, { useContext, useEffect, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, Merged, PerspectiveCamera, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const context = React.createContext();

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/glbs/cattlebuilding_v3-transformed.glb');
  const instances = React.useMemo(
    () => ({
      Bonegarg: nodes.Bone_garg,
      Bonepapo: nodes.Bone_papo,
      WhiteRhino: nodes.White_Rhino,
      Cube: nodes.Cube003,
      Cube1: nodes.Cube041,
      Plane: nodes.Plane024,
      Roof: nodes.Roof,
      Betweenwood: nodes.Between_wood,
      BetweenWalls: nodes.Between_Walls,
      SideWalls: nodes.SideWalls,
      Floor: nodes.Floor,
      Barrier: nodes.Barrier,
      Props: nodes.Props,
      Cube2: nodes.Cube006,
      Plane1: nodes.Plane028,
      Plane2: nodes.Plane028_1,
      InsideFloor: nodes.Inside_Floor,
      EntranceWallsPlusDetails: nodes.EntranceWalls_Plus_Details,
      Cube3: nodes.Cube022,
      Cube4: nodes.Cube022_1,
      InsideBarrier: nodes.Inside_Barrier,
      InsideBetweenWalls: nodes.Inside_Between_Walls,
      AtticFloorDetals: nodes.Attic_Floor_Detals,
      AtticPillars: nodes.Attic_Pillars,
      AtticWall: nodes.Attic_Wall_1,
      AtticBetweenWalls: nodes.Attic_Between_Walls,
      AtticWall1: nodes.Attic_Wall_2,
      AtticOuterWalls: nodes.Attic_Outer_Walls,
      AtticDoors: nodes.Attic_Doors,
      Cube5: nodes.Cube,
      Cube6: nodes.Cube_1,
      BottomWall: nodes.Bottom_Wall_4,
      BottomWall1: nodes.Bottom_Wall_2,
      Triponodeeabccadbbc: nodes['tripo_node_337ea5bc-c595-4267-a15d-92bb618c8818'],
      Triponodedfaadfdbaeabafccb: nodes['tripo_node_6d75f38a-2ad4-4fd3-baea-4b31a56fc8cb'],
      Triponodefbfbbccdfeaadf: nodes['tripo_node_45f9b10f-bb11-41c5-9cd4-72feaad4f236'],
      Kroon: nodes.Kroon,
      BaseTree: nodes.Base_Tree001,
      Zebrai: nodes.zebrai,
      Zebrai1: nodes.zebrai001,
    }),
    [nodes]
  );
  return (
    <Merged
      meshes={instances}
      {...props}>
      {(instances) => (
        <context.Provider
          value={instances}
          children={children}
        />
      )}
    </Merged>
  );
}

export function Model({ children, gltfLoaded, ...props }) {
  const instances = useContext(context);
  const group = useRef();
  const { nodes, animations } = useGLTF('/glbs/cattlebuilding_v3-transformed.glb');
  const { mixer, actions } = useAnimations(animations, group);

  useEffect(() => {
    gltfLoaded(nodes, animations, mixer, actions);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}>
      <group name="Scene">
        {children}
        <group
          name="CamEmpty"
          position={[-11.278, 7.713, -31.93]}
        />
        <primitive object={nodes.Bone_anca} />
        <primitive object={nodes.neutral_bone} />
        <primitive object={nodes.Bone_anca_1} />
        <primitive object={nodes.neutral_bone_1} />
        <PerspectiveCamera
          name="MainCam"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={49.426}
          position={[74.369, 8.657, -48.9]}
          rotation={[-3.086, 1.375, 3.087]}
        />
        <instances.WhiteRhino
          name="White_Rhino"
          position={[28.041, -3.025, -29.816]}
          rotation={[Math.PI / 2, 0, -2.443]}
        />
        <instances.Cube
          name="Cube003"
          position={[-5.39, 3.193, -29.245]}
          scale={0.11}
        />
        <instances.Cube1
          name="Cube041"
          position={[3.565, -1.682, -74.555]}
        />
        <instances.Plane
          name="Plane024"
          position={[-0.7, -2.22, 10.72]}
        />
        <instances.Roof
          name="Roof"
          position={[7.504, 5.718, -9.902]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Betweenwood
          name="Between_wood"
          position={[8.138, 3.143, -39.011]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <instances.BetweenWalls
          name="Between_Walls"
          position={[5.625, 1.702, 0.39]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <instances.SideWalls
          name="SideWalls"
          position={[4.745, -1.424, -70.376]}
        />
        <instances.Floor
          name="Floor"
          position={[5.554, -2.426, -40.223]}
        />
        <instances.Barrier
          name="Barrier"
          position={[13.919, -2.153, -69.6]}
        />
        <instances.Props
          name="Props"
          position={[47.343, -2.544, -31.634]}
        />
        <instances.Cube2
          name="Cube006"
          position={[9.228, -2.191, -32.628]}
        />
        <group
          name="LongWall_2"
          position={[-2.419, -1.47, -30.362]}
          rotation={[0, 0, Math.PI / 2]}>
          <instances.Plane1 name="Plane028" />
          <instances.Plane2 name="Plane028_1" />
        </group>
        <instances.InsideFloor
          name="Inside_Floor"
          position={[5.554, -2.426, -40.223]}
        />
        <instances.EntranceWallsPlusDetails
          name="EntranceWalls_Plus_Details"
          position={[4.745, -1.424, -70.376]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <group
          name="Fontain"
          position={[-1.649, -2.426, -34.536]}>
          <instances.Cube3 name="Cube022" />
          <instances.Cube4 name="Cube022_1" />
        </group>
        <instances.InsideBarrier
          name="Inside_Barrier"
          position={[2.639, -1.456, -67.045]}
        />
        <instances.InsideBetweenWalls
          name="Inside_Between_Walls"
          position={[4.807, -1.334, -8.77]}
        />
        <instances.AtticFloorDetals
          name="Attic_Floor_Detals"
          position={[2.557, 2.822, -35.661]}
        />
        <instances.AtticPillars
          name="Attic_Pillars"
          position={[6.489, 3.399, -38.591]}
        />
        <instances.AtticWall
          name="Attic_Wall_1"
          position={[7.421, 4.945, -34.317]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.AtticBetweenWalls
          name="Attic_Between_Walls"
          position={[2.637, 3.384, -65.033]}
        />
        <instances.AtticWall1
          name="Attic_Wall_2"
          position={[-1.195, 6.587, -38.463]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.AtticOuterWalls
          name="Attic_Outer_Walls"
          position={[2.637, 3.384, 0.3]}
        />
        <instances.AtticDoors
          name="Attic_Doors"
          position={[-2.783, 3.857, -30.273]}
        />
        <group
          name="Bottom_Wall_1"
          position={[8.599, 0.311, -55.598]}>
          <instances.Cube5 name="Cube" />
          <instances.Cube6 name="Cube_1" />
        </group>
        <instances.BottomWall
          name="Bottom_Wall_4"
          position={[8.599, 0.311, -64.921]}
        />
        <instances.BottomWall1
          name="Bottom_Wall_2"
          position={[8.599, 0.311, -0.523]}
        />
        <instances.Triponodeeabccadbbc
          name="tripo_node_337ea5bc-c595-4267-a15d-92bb618c8818"
          position={[-2.293, -0.824, -34.537]}
        />
        <instances.Triponodedfaadfdbaeabafccb
          name="tripo_node_6d75f38a-2ad4-4fd3-baea-4b31a56fc8cb"
          position={[-1.813, -0.792, -31.949]}
        />
        <instances.Triponodefbfbbccdfeaadf
          name="tripo_node_45f9b10f-bb11-41c5-9cd4-72feaad4f236"
          position={[-1.859, -0.791, -37.162]}
        />
        <instances.Kroon
          name="Kroon"
          position={[41.736, 10.053, -25.688]}
          rotation={[2.182, 0.91, -0.919]}
          scale={0.559}
        />
        <instances.BaseTree
          name="Base_Tree001"
          position={[44.811, -2.641, -27.046]}
          rotation={[0, 0.056, 0]}
          scale={1.234}
        />
        <instances.Zebrai name="zebrai" />
        <instances.Zebrai1 name="zebrai001" />
      </group>
    </group>
  );
}

useGLTF.preload('/glbs/cattlebuilding_v3-transformed.glb');
